### ISSUE TITLE
Game Pass International Support

### ISSUE THREAD

**Issue by aqw** [pigskin/pigskin#1] opened 2018-08-15 13:08 UTC
Much of this content comes from aqw/xbmc-gamepass#313

---

A quick background for the uninitiated:

In 2017, the Game Pass Service was split between two streaming providers:

    Game Pass Europe (WPP/Bruin)
    Game Pass International (NeuLion)

Currently all developers of this library are in Europe, so only Game Pass Europe is supported. We are very interested in developers from Game Pass International regions getting involved in development and maintenance.

In theory, it should not be too difficult to get decent support for Game Pass International. Prior to 2017, NeuLion was the only streaming provider. Version 0.10.2 of aqw/xbmc-gamepass used that service. As a result, many of the devs have experience with the NeuLion service, and we can help provide some pointers.

However, not all is easy. Predictably, NeuLion has changed its APIs quite a bit since the split (likely concern over the competition), so it's not as easy as a quick code-resuscitation. There will likely be some new paths to blaze.

It is important that consumers of pigskin.py should be able to use the same API regardless of which service (Europe vs International) they are connecting to. This will be problematic at times, but looks to be doable.

Two places where you can borrow code from
* pigskin.py from xbmc-gamepass 0.10.2
* dav-sap did some work in the international-support-2017 branch of dav-sap/xbmc-gamepass

**Comment by r3dlobst3r** [comment] 2018-08-23 18:06
I am willing to share a login for game pass international

**Comment by aqw** [comment] 2018-08-23 18:15
@r3dlobst3r Thanks for the offer. When it comes time to start integrating dev-sap's work into this library, I may ask for you to do some testing. :-)

**Comment by michlinux** [comment] 2018-08-29 03:36
I have tried @dav-sap 's fork.. NFL network works but has issues (every 15secs or so it pauses and resumes after 2sec or so... ) However I am unable to get games to reply in any format... Looking in debug log its giving me a 403 error. Next live game I will check those... I have a full Gamepass account and currently in New Zealand, I am happy to help with testing, etc... I do know a bit of python however I am far from an expert, but I have no experience with writing addons for kodi.

**Comment by dav-sap** [comment] 2018-08-29 04:56
I will take a look. I remember it worked last season. The lagging doesn't
sound like some i experienced. Did u ise adaptive inputstream? enabled it
in the setting

**Comment by michlinux** [comment] 2018-08-29 13:25
Yes I am using adaptive, as you stated before it does not work without it. so my memory must have been bad, as I timed between the "pauses" and it looks like its exactly 1min, might be 61secs....  I timed it for 5 times always the same. I grabbed part  of debug log from when it does a pause.. I should clarify; the player doesn't pause, the screen goes black and I see a file flash like its starting a new file in the upper left, but its really fast. 1 second maybe, 2 max... most of that the screen is just black.
[gamepass.log](https://github.com/aqw/pigskin/files/2332264/gamepass.log)

**Comment by michlinux** [comment] 2018-08-31 02:38
Tested on live games both with and without adaptive and neither work.

**Comment by michlinux** [comment] 2018-09-10 00:28
Yep this is live game from today... 
Logging starts from app launch to attempted live game play. Adaptive is on.
[kodi.log](https://github.com/aqw/pigskin/files/2364801/kodi.log)

**Comment by aqw** [comment] 2018-09-11 20:10
Once #15 is done, then we can actively start working on this.

**Comment by dav-sap** [comment] 2018-09-11 20:14
For now, everything seems to be broken again. Except for nfl network. I
don't know what changed, the log doesn't say much. If anybody can help me
with this let me know.

**Comment by dav-sap** [comment] 2018-09-15 06:45
i got replays to work. without using inputstream adaptive, which seems to be broken now. inputstream adaptive seems to forget the cookies and it get 403 back. I will to work it with them ( i remember doing the same thing last year) 
I believe the live will work tomorrow now that i understood the problem. but can't promise anything. I committed the changes to my fork

**Comment by michlinux** [comment] 2018-09-17 16:58
Yes, they are working here as well, nicely done! Cheers m8, is adaptive bug the reason NFL network was doing the small freezes? - on a side note I have more free time now, so I can help with this project now.

**Comment by michlinux** [comment] 2018-09-18 00:09
So it looks like Live is going to work... Monday Night game is getting ready to start, and its showing "The Game will start soon" screen.

**Comment by dav-sap** [comment] 2018-09-18 04:33
now we need to clean everything up and fit to the new  API @aqw is writing.
at the time i also changed the default.py file which should stay the same

On Sep 18, 2018 03:09, "michlinux" <notifications@github.com> wrote:

So it looks like Live is going to work... Monday Night game is getting
ready to start, and its showing "The Game will start soon" screen.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aqw/pigskin/issues/1#issuecomment-422210787>, or mute
the thread

**Comment by aqw** [comment] 2018-09-18 06:39
@dav-sap Thanks for continuing to keep the International support alive. :-)

@michlinux You say you have time, eh? :-D Help's always appreciated. If your focus is international support, then @dav-sap is right that it's best to wait until I have the new API figured out (which hopefully won't be too much longer). If your interest is broader and feel comfortable working in Python, then find something you're interested in the issues and I can provide some direction. :-)

**Comment by r3dlobst3r** [comment] 2018-09-18 15:00
@dav-sap @michlinux How were you able to get the addon to work in the new version of Kodi, with the updated version of input? Kodi will not allow me to enable it. Thanks!

**Comment by dav-sap** [comment] 2018-09-18 15:10
not sure i did anything special, but i handled this almost a yr ago, maybe
i don't remember.  what logs do you get?

**Comment by r3dlobst3r** [comment] 2018-09-18 15:16
@dav-sap sorry i was referring to this part:
note: default inputstream adaptive for kodi17 is version 2.0.19, this issue (cookies not being sent in all requests) has been fixed in later versions. in kodi18 they use the latest version. need to manually update version so inputstream adaptive works

**Comment by r3dlobst3r** [comment] 2018-09-18 15:38
Yeah, sorry for being too vague.

**Comment by dav-sap** [comment] 2018-09-18 15:57
kodi18 has the latest. To put the latest on kodi17 you need to build it on
your own. but from some version it's not compatible at all with 17. you
should check their github and issues.

**Comment by r3dlobst3r** [comment] 2018-09-18 15:59
Okay, thanks @dav-sap .

**Comment by michlinux** [comment] 2018-09-18 21:51
@aqw You bet! I have "some" free time now starting this coming weekend. Im happy to help and my python skills are improving, so will see what I can do. cheers.

**Comment by aqw** [comment] 2018-09-19 12:03
@michlinux Great to hear. I'm actually leaving for a week-long vacation tomorrow, so I'll be taking a break during that period. But I'll be happy to answer any questions when I come back. :-)

**Comment by dav-sap** [comment] 2019-08-18 04:44
Hey all,
I can confirm international game pass works with https://github.com/aqw/xbmc-gamepass master code.
I used kodi 18 with inputstream adaptive. From what i read i think europe also has the problem they must use inputstream adaptive. 
I checked: shows, nfl network live, live game, replays.

**Comment by Fooboss** [comment] 2020-01-12 22:27
@dav-sap Any way you could share how you installed the NFL Gamepass add-on into Kodi 18? Based on the discussion in this thread, I just tried updating to Kodi 18 but the NFL Gamepass add-on was reported as incompatible. Does it need to be installed manually somehow, rather than through the Kodi add-ons interface?

**Comment by CraigMack69** [comment] 2022-08-18 16:59
If needed I can provide international gp account for a dev.

**Comment by Brandon1212b** [comment] 2022-09-05 19:01
Is game pass international support working for this or https://github.com/pigskin/kodi-gamepass?

**Comment by jm-duke** [comment] 2022-09-05 21:29
I don't know, if this still is an issue. Please see my comments in https://github.com/pigskin/kodi-gamepass/issues/444

**Comment by jm-duke** [comment] 2023-06-29 21:12
Closing this issue, as NFL has canceled the Gamepass service

**Closed by jm-duke** 2023-06-29 21:12 UTC
Labels: 0.4.0
